[client]
    serverName = "mp-gateway"
    serverVersion = "v0.0.1"
    configCenterHost = "http://cx-config-center-svc.cx-rpc-base:8000"

[server]
    httpPort = 8008
    tcpPort = 7008
    rpcOpen = false
    receiveSocketChanLen = 100
    receiveTcpMsgChanLen = 100