[server]
    tcpPort = 9001
    httpPort = 7001
    receiveSocketChanLen = 100
    receiveServiceConnChanLen = 120

[redis]
    host = "localhost:6379"
    pwd = ""
    index = 0

[timeWheel]
    cap = 20
    noticeChanLen = 200